version: '2'
services:
  db:
    build: db
    environment:
      - MYSQL_DATABASE=konsultkartan
      - MYSQL_USER=konsultkartan
      - MYSQL_PASSWORD=secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306

  web:
    build: web
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080
